In [1]:
import tensorflow as tf

In [10]:
a = tf.constant(10.5, tf.float64)
a

<tf.Tensor: shape=(), dtype=float64, numpy=10.5>

In [16]:
b = tf.constant(20, dtype=tf.float64)
b

<tf.Tensor: shape=(), dtype=float64, numpy=20.0>

In [18]:
c = tf.add(a, b)
c

<tf.Tensor: shape=(), dtype=float64, numpy=30.5>

In [20]:
d = a + b
d

<tf.Tensor: shape=(), dtype=float64, numpy=30.5>

In [22]:
e = tf.Variable([10, 20], dtype=tf.float64)
e

<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([10., 20.])>

In [24]:
f = tf.Variable([30, 60], dtype=tf.float64)
f

<tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([30., 60.])>

In [26]:
g = e + f
g

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([40., 80.])>

In [29]:
@tf.function
def soma_quadrado( a, b ):
    return a ** 2 + b ** 2

In [30]:
soma_quadrado( 2, 3 )

<tf.Tensor: shape=(), dtype=int32, numpy=13>